import { Inter, DM_Sans } from "next/font/google";
import "./globals.scss";

const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
});

const DMSans = DM_Sans({
  variable: "--DMSans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${DMSans.variable}`}>{children}</body>
    </html>
  );
}
